import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import Header from './ui/header';
const hikika = localFont({ src: '../public/OldLondon.ttf', display: 'swap' });
const raleway = Raleway({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-raleway',
});
const hikka = localFont({
	src: '../public/OldLondon.ttf',
	display: 'swap',
	variable: '--font-hikka',
});

const hikkarus = localFont({
	src: '../public/cyrillicgoth.ttf',
	display: 'swap',
	variable: '--font-hikkarus'
})

export const metadata: Metadata = {
	title: 'hikikomori kai',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {


	return (
		<html lang='en' className={`${raleway.variable} ${hikka.variable} ${hikkarus.variable}`}>
			<body >
					<Header />
					<main className='mt-20 flex h-full min-h-screen flex-col'>
					{children}
					</main>
			</body>
		</html>
	);
}
